### ISSUE TITLE
[UX] What is a Categorical Tree?

### ISSUE THREAD

**Issue by sherzinger** [ada-discovery/ada-web#50]
I couldn't get this to do anything for the public datasets.
This looks like a broken feature on first glance, even though I know it's not.

Either hide it if not applicable for a certain data set or let the user know what exactly the issue is.

Right now all I see is that "No Iris Category found"

**Comment by peterbanda** [comment]
You are right. Defining or traversing categories is something more meant for admins and should be hidden for ordinary users. They can actually access categories by using the side (I2B2) tree or in filter pop-ups.

I've updated your permissions to "standard" ones. Pls. check if you can see the categorical tree tab now.
