### ISSUE TITLE
[UX] Ontology tree needs to be better integrated

### ISSUE THREAD

**Issue by sherzinger** [ada-discovery/ada-web#51]
The feature is super new, so it is not well integrated yet.

Suggestions:
- For Drag&Drop highlight the drop zones. As it is now I have a large web interface with no directly identifiable interaction possibilities. (I seriously couldn't get this to do much, despite trying)

- Add small action icons (or similar UX optimisations) and discard single/double clicks on field names (or keep them only for redundancy). Even single click here would be bad, because my brain has to connect what happens on screen with the action I just performed. That's OK for trivial actions, but if things are flashing/ reloading/changing too much, the user will get lost.

- Add number of non-null items for each field (if the elastic queries are not too expensive ;-) )

**Comment by peterbanda** [comment]
number of non-null items (point 3) can be displayed in the tree by checking "[x] Filter Show Non-Null Count" in the setting of a target data set

**Comment by peterbanda** [comment]
Drag&drop highlighting (point 1) has been resolved by PR https://github.com/ada-discovery/ada-web/pull/75

**Comment by peterbanda** [comment]
The point 2 continues in ada-discovery/ada-issues#33 (more detail specification needed)
